spring.application.name=TulaHack
server.port=8080

# SQLite
spring.datasource.url=jdbc:sqlite:routes.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# C++ оптимизатор
cpp.optimizer.path=./build/route_solver
cpp.optimizer.input=./build/optimizer_input.json
cpp.optimizer.output=./build/optimizer_output.json

# 2GIS API
twogis.api.url=https://catalog.api.2gis.com
twogis.api.key=YOUR_KEY_HERE

# OpenRouteService API ключ
ors.api.key=YOUR_KEY_HERE

# Таймаут WebClient (секунды)
webclient.timeout.seconds=10
